import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
test('original models remain bundled',()=>{const d=JSON.parse(read('public/models/sculpture-wireframes.json'));assert.equal(d.groups.length,5);assert.equal(d.groups.reduce((n,g)=>n+g.edges.length/6,0),5789);assert.ok(existsSync(new URL('../public/models/three-gorges.glb',import.meta.url)));});
test('only pause and about controls remain',()=>{const h=read('index.html');for(const id of ['pause','about','about-open','about-close','about-return'])assert.ok(h.includes(`id="${id}"`));for(const obsolete of ['id="reset"','id="sound"','id="elapsed"','id="contact"','拖动作品'])assert.ok(!h.includes(obsolete));});
test('no pointer gesture or visitor action is needed',()=>{const code=read('src/main.js');for(const x of ['pointerdown','pointermove','holdPiece','moveHeld','Math.random'])assert.ok(!code.includes(x));assert.ok(code.includes('requestAnimationFrame(frame)'));});
test('no tracking, external request, or browser storage',()=>{const code=read('src/main.js')+read('index.html')+read('src/style.css');for(const x of ['fetch(','localStorage','sessionStorage','sendBeacon','XMLHttpRequest','fonts.googleapis'])assert.ok(!code.includes(x));});
test('relative production paths and Pages marker are valid',()=>{assert.ok(read('vite.config.js').includes("base: './'"));assert.ok(existsSync(new URL('../public/.nojekyll',import.meta.url)));});
test('motion preferences and interrupted viewing are handled',()=>{const code=read('src/main.js');for(const x of ['prefers-reduced-motion','visibilitychange','about.open','last=performance.now()'])assert.ok(code.includes(x));});
test('visual palette remains strictly grayscale',()=>{const code=read('src/style.css')+read('src/renderer.js');for(const match of code.matchAll(/#([0-9a-f]{6})(?:[0-9a-f]{2})?\b/gi)){const h=match[1];assert.equal(h.slice(0,2),h.slice(2,4));assert.equal(h.slice(0,2),h.slice(4,6));}});
