import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync,existsSync}from'node:fs';const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
test('original GLB and five wireframe groups stay bundled',()=>{assert.ok(existsSync(new URL('../public/models/three-gorges.glb',import.meta.url)));assert.equal(JSON.parse(read('public/models/sculpture-wireframes.json')).groups.length,5);});
test('all filled geometry comes from the verified source triangle asset',()=>{const d=JSON.parse(read('public/models/sculpture-faces.json'));assert.equal(d.groups.length,5);assert.equal(d.groups.reduce((n,g)=>n+g.triangles.length/9,0),2000);assert.ok(read('src/print-renderer.js').includes('triangleArea'));});
test('the autonomous process has optional navigation and ripple without a gather task',()=>{const m=read('src/main.js');for(const x of ['requestAnimationFrame(frame)','advance(state,dt*PLAYBACK_RATE)','pointercancel','lostpointercapture'])assert.ok(m.includes(x));for(const x of ['setGather','holdStart'])assert.ok(!m.includes(x));});
test('iOS callout suppression remains canvas scoped and explanation selectable',()=>{const css=read('src/style.css'),m=read('src/main.js');assert.ok(css.includes('touch-action:none'));assert.ok(css.includes('-webkit-touch-callout:none'));assert.ok(css.includes('-webkit-user-select:text;user-select:text;-webkit-touch-callout:default'));assert.ok(m.includes("canvas.addEventListener('contextmenu'"));assert.ok(!m.includes("document.addEventListener('contextmenu'"));});
test('no private data, analytics, requests, storage, or AI calls',()=>{const s=read('src/main.js')+read('index.html');for(const x of ['fetch(','sendBeacon','localStorage','sessionStorage','XMLHttpRequest'])assert.ok(!s.includes(x));});
test('pause, reduced motion, interruption and about handling are present',()=>{const m=read('src/main.js');for(const x of ['prefers-reduced-motion','visibilitychange','document.hidden||about.open','state.paused','cancelGestures'])assert.ok(m.includes(x));});
test('Pages-relative paths stay supported',()=>{assert.ok(read('vite.config.js').includes("base: './'"));assert.ok(existsSync(new URL('../public/.nojekyll',import.meta.url)));});

test('ongoing random intake and adaptive budgeting are explicit',()=>{const s=read('src/main.js');for(const x of ['crypto.getRandomValues','setBudget','drawCost','dataset.closed','dataset.materials'])assert.ok(s.includes(x));assert.ok(read('index.html').includes('物理金属'));});

test('real PBR path is primary and compatibility fallback is explicitly disclosed',()=>{const m=read('src/main.js'),p=read('src/pbr-renderer.js');for(const x of ['webgl2Available','PbrArchive.create','兼容线稿','canvas-fallback'])assert.ok(m.includes(x));for(const x of ['MeshPhysicalMaterial','PMREMGenerator','RoomEnvironment','InstancedMesh','setMorphAt','PCFSoftShadowMap'])assert.ok(p.includes(x));assert.ok(read('index.html').includes('设备不支持时会明确标注'));});

test('new flight runs autonomously and ripple has a keyboard equivalent',()=>{const m=read('src/main.js');for(const x of ['PLAYBACK_RATE=1.55','automaticCamera(viewTime,innerWidth<650)','now-touched<2400',"key==='Enter'",'advanceRipples','emitRipple','state.reducedMotion'])assert.ok(m.includes(x));});
