import{test}from'node:test';import assert from'node:assert/strict';import{GestureController}from'../src/gestures.js';import{createCamera,orbitCamera,panCamera,zoomCamera,resetCamera}from'../src/camera.js';
function fixture(){const events=[];const g=new GestureController(Object.fromEntries(['tap','holdStart','holdEnd','orbit','pan','zoom'].map(k=>[k,(...a)=>{events.push([k,...a]);return true;}])));return{g,events};}
test('short stationary touch is exactly one tap',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.tick(100);g.up(1);assert.deepEqual(events,[['tap',100,100]]);});
test('drag rotates and does not trigger tap or hold',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.move({id:1,x:140,y:120});g.tick(700);g.up(1);assert.deepEqual(events,[['orbit',40,20]]);});
test('long press gathers once and releases once',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.tick(500);g.tick(700);g.up(1);assert.deepEqual(events,[['holdStart',100,100],['holdEnd']]);});
test('moving after a hold releases it and starts orbit',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.tick(500);g.move({id:1,x:130,y:100});g.up(1);assert.deepEqual(events,[['holdStart',100,100],['holdEnd'],['orbit',30,0]]);});
test('second finger cancels a hold before pinch',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.tick(500);g.down({id:2,x:200,y:100,now:550});g.move({id:2,x:300,y:100});assert.deepEqual(events.slice(0,2),[['holdStart',100,100],['holdEnd']]);assert.deepEqual(events.slice(2),[['pan',50,0],['zoom',2]]);});
test('remaining finger after pinch never fires a tap',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.down({id:2,x:200,y:100,now:10});g.up(2);g.up(1);assert.equal(events.length,0);});
test('pointer cancellation and focus loss cannot leave gathering active',()=>{const{g,events}=fixture();g.down({id:1,x:100,y:100,now:0});g.tick(500);g.cancel();g.up(1);assert.deepEqual(events,[['holdStart',100,100],['holdEnd']]);assert.equal(g.pointers.size,0);assert.equal(g.mode,'idle');});
test('cancelled short press never ripples',()=>{const{g,events}=fixture();g.down({id:1,x:0,y:0,now:0});g.up(1,true);assert.equal(events.length,0);});
test('right drag pans instead of orbiting',()=>{const{g,events}=fixture();g.down({id:1,x:0,y:0,button:2,now:0});g.move({id:1,x:20,y:30});g.up(1);assert.deepEqual(events,[['pan',20,30]]);});
test('camera zoom, pan and pitch remain bounded and resettable',()=>{const c=createCamera();orbitCamera(c,20,10000);zoomCamera(c,100);panCamera(c,10000,-10000,320,568);assert.equal(c.pitch,1.15);assert.equal(c.zoom,2.6);assert.equal(c.panX,.48);assert.equal(c.panY,-.48);zoomCamera(c,.0001);assert.equal(c.zoom,.55);resetCamera(c);assert.deepEqual(c,createCamera());});

test('tap-only mode never loses a stationary touch to an absent hold action',()=>{const events=[],g=new GestureController({tap:(...x)=>events.push(x)});g.down({id:1,x:10,y:20,now:0});g.tick(900);g.up(1);assert.deepEqual(events,[[10,20]]);});
