import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {makePhysicalMaterials,inspectionCamera,matrixForPose,effectiveStage,MAX_GPU_INSTANCES} from '../src/pbr-renderer.js';
import {project,getView,transformPoint,instancePose,automaticCamera} from '../src/print-renderer.js';
import {makeInstance} from '../src/archive.js';

test('metal, roughness and glass are real physically based Three.js materials',()=>{const m=makePhysicalMaterials();assert.ok(m.every(x=>x.isMeshStandardMaterial));assert.equal(m[0].metalness,1);assert.ok(m[1].roughness>.8);assert.ok(m[2].isMeshPhysicalMaterial);assert.ok(m[2].transmission>.9);assert.ok(m[2].ior>1.3&&m[2].thickness>0);assert.ok(m[0].roughness<m[3].roughness);m.forEach(x=>x.dispose());});
test('phone glass reduces physical transmission cost without replacing it with fake alpha',()=>{const m=makePhysicalMaterials({phone:true});assert.ok(m[2].transmission>.5);assert.equal(m[2].opacity,1);assert.equal(m[2].transparent,false);m.forEach(x=>x.dispose());});
test('GPU transforms match the preserved Canvas view and source layout',()=>{for(let i=1;i<20;i++){const pose=instancePose(makeInstance(i,0),i%2===0),m=matrixForPose(pose),p=[.3,-.4,.8],actual=new THREE.Vector3(...p).applyMatrix4(m).toArray(),expected=transformPoint(p,pose);actual.forEach((n,j)=>assert.ok(Math.abs(n-expected[j])<1e-10));}});
test('PBR camera matches registration-overlay projection exactly',()=>{for(const[w,h]of[[390,844],[1188,762],[1440,1000]])for(const c of [{yaw:0,pitch:0,zoom:1,panX:0,panY:0},{yaw:-.5,pitch:.3,zoom:1.3,panX:.12,panY:-.08}]){const s=inspectionCamera(w,h,c),cam=new THREE.OrthographicCamera(s.left,s.right,s.top,s.bottom,.1,150);cam.position.copy(s.eye);cam.up.copy(s.up);cam.lookAt(s.target);cam.updateProjectionMatrix();cam.updateMatrixWorld(true);for(const p of[[1,2,3],[-4,-1,5],[8,3,-6]]){const q=new THREE.Vector3(...p).project(cam),raw=project(p,c);assert.ok(Math.abs((q.x+1)*w/2-(s.view.cx+raw[0]*s.view.scale))<1e-8);assert.ok(Math.abs((1-q.y)*h/2-(s.view.cy+raw[1]*s.view.scale))<1e-8);}}});
test('completed morph commits select the genuinely reduced stage',()=>{assert.equal(effectiveStage({stage:2,committed:false}),2);assert.equal(effectiveStage({stage:2,committed:true}),3);assert.equal(effectiveStage({stage:6,committed:true}),6);});
test('instanced morph weights are per-instance and allocate a bounded texture',()=>{const geometry=new THREE.BoxGeometry();geometry.morphAttributes.position=[geometry.attributes.position.clone()];geometry.morphAttributes.normal=[geometry.attributes.normal.clone()];const dummy=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial()),batch=new THREE.InstancedMesh(geometry,dummy.material,MAX_GPU_INSTANCES);dummy.morphTargetInfluences[0]=.2;batch.setMorphAt(0,dummy);dummy.morphTargetInfluences[0]=.8;batch.setMorphAt(5,dummy);assert.equal(batch.morphTexture.image.height,MAX_GPU_INSTANCES);const a=batch.morphTexture.image.data;assert.ok(Math.abs(a[1]-.2)<1e-6);assert.ok(Math.abs(a[11]-.8)<1e-6);batch.dispose();geometry.dispose();dummy.material.dispose();});

test('actual-GLB render batching keeps counts, morphs and retirement bounded without a GPU claim',async()=>{
  const {readFileSync}=await import('node:fs');const {GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');const {extractSourceGeometries}=await import('../src/mesh-source.js');const {PbrArchive}=await import('../src/pbr-renderer.js');const {ArchivePrint}=await import('../src/print-renderer.js');const {stateAt,createState}=await import('../src/archive.js');const {prepareSurfacePatches,phaseInfo}=await import('../src/surface-patches.js');
  const data=JSON.parse(readFileSync(new URL('../public/models/sculpture-wireframes.json',import.meta.url))),glb=readFileSync(new URL('../public/models/three-gorges.glb',import.meta.url)),loaded=await new GLTFLoader().parseAsync(glb.buffer.slice(glb.byteOffset,glb.byteOffset+glb.byteLength),'');
  const p=Object.create(PbrArchive.prototype),ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});p.overlay=new ArchivePrint({getContext:()=>ctx},data.groups,[],{overlayOnly:true});p.overlay.resize(1188,762);p.width=1188;p.height=762;p.camera={yaw:0,pitch:0,zoom:1,panX:0,panY:0};p.sources=extractSourceGeometries(loaded.scene,data);p.scene=new THREE.Scene();p.viewCamera=new THREE.OrthographicCamera();p.buckets=new Map();p.materials=makePhysicalMaterials();p.engine={setScissorTest(){},clear(){},setScissor(){},render(){}};
  const arrays=p.sources.map(s=>s.stages.map(t=>t.positions));for(const time of[0,5,20,40,60,120,240,600]){const state=stateAt(time,{budget:26,initialCount:12});p.camera=automaticCamera(time*.7);p.draw(state);assert.ok(p.viewCamera.isPerspectiveCamera);const expected=p.frames.reduce((n,f)=>n+(f.edgeCount?prepareSurfacePatches(p.sources[f.instance.modelIndex])[effectiveStage(f)].reduce((sum,g,patch)=>sum+(Math.round(phaseInfo(f.instance.key,patch,state.elapsed).surfaceAlpha*12)>0?g.userData.triangleCount:0),0):0),0);assert.equal(p.triangleCount,expected);assert.ok(p.buckets.size<=state.instances.length*3);assert.ok([...p.buckets.values()].reduce((n,b)=>n+b.mesh.count,0)<=p.renderedInstances*3);assert.equal(p.renderedSegments,p.overlay.renderedSegments);assert.equal(p.renderedPoints,p.overlay.renderedPoints);assert.ok(p.renderedSegments<=7200&&p.renderedPoints<=580);for(const b of p.buckets.values()){assert.ok(b.mesh.isInstancedMesh);assert.equal(b.mesh.morphTexture.image.height,32);assert.equal(b.mesh.geometry.morphAttributes.position.length,1);}}
  const {createRippleState,emitRipple,advanceRipples}=await import('../src/ripple.js');const live=createState({initialCount:12});live.ripples=createRippleState();p.draw(live);const before=p.triangleCount,positions=[...p.overlay.poses.values()].map(x=>x.position.slice());emitRipple(live.ripples,[0,-.65,0]);advanceRipples(live.ripples,1);p.draw(live);assert.equal(p.triangleCount,before);assert.ok([...p.overlay.poses.values()].some((x,i)=>Math.hypot(...x.position.map((v,j)=>v-positions[i][j]))>.1));
  const empty=createState({budget:26,initialCount:12});empty.elapsed=100;p.draw(empty);assert.equal(p.triangleCount,0);assert.equal(p.renderedInstances,0);assert.equal(p.buckets.size,0);assert.equal(p.renderedSegments,0);assert.equal(p.renderedPoints,0);p.sources.forEach((s,i)=>s.stages.forEach((t,j)=>assert.equal(t.positions,arrays[i][j])));p.strokes.dispose();for(const m of p.layerMaterials.values())m.dispose();for(const source of p.sources)for(const stage of prepareSurfacePatches(source))for(const g of stage)g.dispose();p.materials.forEach(m=>m.dispose());p.sources.forEach(s=>s.stageGeometries.forEach(g=>g.dispose()));
});
