import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{ArchivePrint,project,automaticCamera,instancePose,getView,placeLabelY}from'../src/print-renderer.js';import{stateAt,makeInstance}from'../src/archive.js';import{createCamera,orbitCamera}from'../src/camera.js';
const groups=JSON.parse(readFileSync(new URL('../public/models/sculpture-wireframes.json',import.meta.url))).groups,faces=JSON.parse(readFileSync(new URL('../public/models/sculpture-faces.json',import.meta.url))).groups;
const ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
test('renderer uses Canvas2D without GPU and admits changing numbers of shapes',()=>{const r=new ArchivePrint({getContext:type=>{assert.equal(type,'2d');return ctx;}},groups,faces);r.resize(1188,762,1);r.draw(stateAt(0));assert.equal(r.frames.length,10);r.draw(stateAt(30));assert.ok(r.frames.length>10);});
test('rightward and upward dragging move a front-side point in natural directions',()=>{const c=createCamera(),point=[0,0,5],before=project(point,c);orbitCamera(c,30,0);assert.ok(project(point,c)[0]>before[0]);const u=createCamera();orbitCamera(u,0,-30);assert.ok(project(point,u)[1]<before[1]);});
test('instance placements and sizes vary deterministically',()=>{assert.deepEqual(instancePose(makeInstance(4,0)),instancePose(makeInstance(4,0)));assert.notDeepEqual(instancePose(makeInstance(4,0)),instancePose(makeInstance(5,0)));});
test('automatic camera moves continuously without time jumps',()=>{assert.notDeepEqual(automaticCamera(0),automaticCamera(20));for(let t=0;t<100;t+=.3){const a=automaticCamera(t),b=automaticCamera(t+.01);assert.ok(Math.abs(a.yaw-b.yaw)<.003);assert.ok(Math.abs(a.pitch-b.pitch)<.003);}});
test('labels stay legible and on-screen through sparse/dense phone and desktop scenes',()=>{for(const[w,h]of[[320,568],[390,844],[768,1024],[1188,762],[1440,1000],[844,390]]){const r=new ArchivePrint({getContext:()=>ctx},groups,faces);r.resize(w,h,1);for(const t of [0,23,60,120,240,600]){r.camera=automaticCamera(t);r.draw(stateAt(t,{budget:w<650?7:14}));for(const p of r.labels){assert.ok(p.x>=16&&p.x<w-80);assert.ok(p.y>=0&&p.y<=getView(w,h).bottom);}assert.ok(r.labels.length>=Math.min(3,r.frames.length));assert.ok(r.facetCount<=2400);assert.ok(getView(w,h).scale>0);}}});
test('bounded distant bundles retain exactly the closed registry count',()=>{const r=new ArchivePrint({getContext:()=>ctx},groups,faces);r.resize(1188,762);const s=stateAt(3600);r.draw(s);assert.equal(r.bundleRecords,s.closed);assert.ok(r.bundleCount<=64);assert.ok(r.hatchCount<=r.facetCount*5);});
test('nearby phone ID labels are separated rather than covered',()=>{const y=placeLabelY(195,190,110,[{x:260,y:190}],120,650);assert.ok(Math.abs(y-190)>=23);});


test('only selected model vertices and curve points scatter while every instance pose and other geometry stay fixed',async()=>{const{createRippleState,emitRipple,advanceRipples}=await import('../src/ripple.js');const r=new ArchivePrint({getContext:()=>ctx},groups,faces);r.resize(1188,762);const state=stateAt(0,{initialCount:12});state.paused=true;state.ripples=createRippleState();r.camera=automaticCamera(0);r.draw(state);const before=r.summary.edges,poses=[...r.poses.values()].map(p=>p.position.slice()),fields=structuredClone(r.fields),target=r.centralTarget();assert.ok(target);assert.ok(r.pick(...target.center.slice(0,2)));emitRipple(state.ripples,{serial:target.serial,origin:target.local});advanceRipples(state.ripples,.2,{paused:true});r.draw(state);assert.equal(r.summary.edges,before);assert.deepEqual([...r.poses.values()].map(p=>p.position),poses);for(let i=0;i<fields.length;i++){if(fields[i].serial===target.serial)assert.notDeepEqual(r.fields[i].curves,fields[i].curves);else assert.deepEqual(r.fields[i],fields[i]);}advanceRipples(state.ripples,10,{paused:true});r.draw(state);assert.deepEqual(r.fields,fields);state.elapsed=100;r.draw(state);assert.equal(r.summary.edges,0);assert.equal(r.centralTarget(),null);assert.equal(r.pick(590,400),null);});

test('front-side perspective inspection follows rightward and upward finger movement',async()=>{const{cameraBasis}=await import('../src/flight-camera.js');const c=automaticCamera(4),b=cameraBasis(c),point=b.target.map((v,i)=>v+b.direction[i]*5),before=project(point,c);const right={...c};orbitCamera(right,30,0);assert.ok(project(point,right)[0]>before[0]);const up={...c};orbitCamera(up,0,-30);assert.ok(project(point,up)[1]<before[1]);});

test('actual rendered curve coordinates change within five seconds even with fixed camera and fixed logical topology',()=>{const r=new ArchivePrint({getContext:()=>ctx},groups,faces,{overlayOnly:true});r.resize(1188,762);const s=stateAt(0,{initialCount:12});r.draw(s);const first=r.fields.flatMap(f=>f.curves.flatMap(c=>c.points.flat())),edges=r.summary.edges;s.elapsed=4;r.draw(s);assert.equal(r.summary.edges,edges);const next=r.fields.flatMap(f=>f.curves.flatMap(c=>c.points.flat()));assert.ok(first.some((v,i)=>Math.abs(v-next[i])>.01));const paused=JSON.stringify(r.fields);r.draw(s);assert.equal(JSON.stringify(r.fields),paused);assert.ok(r.renderedSegments>0&&r.renderedPoints===0);});
test('no visible points exist in desktop or mobile frames, including local ripple',async()=>{const{createRippleState,emitRipple,advanceRipples}=await import('../src/ripple.js');for(const [w,h] of [[390,844],[1188,762]]){const r=new ArchivePrint({getContext:()=>ctx},groups,faces);r.resize(w,h);const s=stateAt(0,{initialCount:8});s.ripples=createRippleState();r.draw(s);const target=r.centralTarget();assert.ok(target);emitRipple(s.ripples,{serial:target.serial,origin:target.local});for(const t of[0,.033,.16,.9]){advanceRipples(s.ripples,t);s.elapsed=t;r.draw(s);assert.equal(r.renderedPoints,0);assert.ok(r.fields.every(f=>f.points.length===0));assert.ok(r.renderedSegments>0);}}});
