import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{ArchivePrint,project,automaticCamera,instancePose,getView,worldPoint,placeLabelY}from'../src/print-renderer.js';import{stateAt,CYCLE}from'../src/archive.js';import{createCamera,orbitCamera}from'../src/camera.js';
const groups=JSON.parse(readFileSync(new URL('../public/models/sculpture-wireframes.json',import.meta.url))).groups,faces=JSON.parse(readFileSync(new URL('../public/models/sculpture-faces.json',import.meta.url))).groups;
const ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
test('renderer uses Canvas2D without requiring a GPU',()=>{const r=new ArchivePrint({getContext:type=>{assert.equal(type,'2d');return ctx;}},groups,faces);r.resize(1188,762,1);r.draw(stateAt(20));assert.equal(r.frames.length,5);});
test('rightward dragging moves a recognizable front-side point right',()=>{const c=createCamera(),point=[0,0,5],before=project(point,c);orbitCamera(c,30,0);assert.ok(project(point,c)[0]>before[0]);});
test('upward dragging moves a recognizable front-side point up',()=>{const c=createCamera(),point=[0,0,5],before=project(point,c);orbitCamera(c,0,-30);assert.ok(project(point,c)[1]<before[1]);});
test('each intake uses deterministic varied scales and rotations',()=>{for(let i=0;i<5;i++){assert.deepEqual(instancePose(i,3),instancePose(i,3));assert.notDeepEqual(instancePose(i,2),instancePose(i,3));}assert.notDeepEqual(instancePose(0,1),instancePose(1,1));});
test('automatic camera moves gently without discontinuous jumps',()=>{assert.notDeepEqual(automaticCamera(0),automaticCamera(20));for(let t=0;t<100;t+=.3){const a=automaticCamera(t),b=automaticCamera(t+.01);assert.ok(Math.abs(a.yaw-b.yaw)<.001);assert.ok(Math.abs(a.pitch-b.pitch)<.001);}});
test('all labels stay on-screen in six viewport sizes and several phases',()=>{for(const[w,h]of[[320,568],[390,844],[768,1024],[1188,762],[1440,1000],[844,390]]){const r=new ArchivePrint({getContext:()=>ctx},groups,faces);r.resize(w,h,1);for(const t of [0,23,43,62,84,CYCLE*5+13]){r.camera=automaticCamera(t);r.draw(stateAt(t));for(const p of r.labels){assert.ok(p.x>=16&&p.x<w-80);assert.ok(p.y>=0&&p.y<h-110);}assert.ok(getView(w,h).scale>0);}}});
test('empty frames keep their world placement rather than shrinking to fit',()=>{const r=new ArchivePrint({getContext:()=>ctx},groups,faces);r.resize(1188,762,1);r.draw(stateAt(0));const a=r.labels.map(p=>[p.x,p.y]);r.draw(stateAt(62));assert.deepEqual(r.labels.map(p=>[p.x,p.y]),a);assert.equal(r.summary.edges,0);});

test('nearby mobile registration labels are vertically separated',()=>{const y=placeLabelY(195,190,110,[{x:260,y:190}],120,650);assert.ok(Math.abs(y-190)>=25);});
