import {MATERIAL_KINDS} from '../src/materials.js';
import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{prepareArchive,instanceFrame,summary,createState,advance,stateAt,makeInstance,setBudget,archiveBundles,desiredDensity,triangleArea,compactEdges,STEPS}from'../src/archive.js';
const data=JSON.parse(readFileSync(new URL('../public/models/sculpture-wireframes.json',import.meta.url))),faces=JSON.parse(readFileSync(new URL('../public/models/sculpture-faces.json',import.meta.url))),models=prepareArchive(data.groups,faces.groups),frames=s=>s.instances.map(i=>instanceFrame(models[i.modelIndex],i,s.elapsed));
test('all five source models preserve their 5,789 exact original edges',()=>{assert.equal(models.length,5);assert.equal(models.reduce((n,m)=>n+m.stages[0].edges.length,0),5789);models.forEach((m,i)=>{for(let e=0;e<m.stages[0].edges.length;e++)for(let j=0;j<2;j++){const p=m.stages[0].vertices[m.stages[0].edges[e][j]],orig=data.groups[i].edges.slice(e*6+j*3,e*6+j*3+3),restore=[p[0]*m.unit,p[1]*m.unit+m.halfY,p[2]*m.unit];restore.forEach((v,k)=>assert.ok(Math.abs(v-orig[k])<.00001));}});});
test('each instance really reduces geometry monotonically to zero',()=>{for(const m of models){let last=Infinity;for(const stage of m.stages){assert.ok(stage.edges.length<last);last=stage.edges.length;assert.equal(compactEdges(stage.vertices,stage.edges).length,stage.edges.length);}const i=makeInstance(m.index+1,0),f=instanceFrame(m,i,i.end-1);assert.equal(f.edgeCount,0);for(const[a,b,c]of m.faces)assert.equal(triangleArea(f.vertices[a],f.vertices[b],f.vertices[c]),0);}});
test('independent instances have varied source types, materials, timing and continuous real morphs',()=>{const items=Array.from({length:50},(_,n)=>makeInstance(n+1,n*3));assert.equal(new Set(items.map(i=>i.modelIndex)).size,5);assert.equal(new Set(items.map(i=>i.materialIndex)).size,10);assert.ok(new Set(items.map(i=>i.stepTime)).size>30);for(const i of items.slice(0,5)){const m=models[i.modelIndex],f=instanceFrame(m,i,i.started+i.intro+2);assert.ok(f.blend>0&&f.blend<1);assert.notDeepEqual(f.vertices,m.stages[0].vertices);}});
test('intake is deterministic by seed and independent of frame update subdivision',()=>{const a=createState({seed:7331}),b=createState({seed:7331});advance(a,240);for(let n=0;n<2400;n++)advance(b,.1);assert.equal(a.records,b.records);assert.deepEqual(a.instances.map(i=>i.serial),b.instances.map(i=>i.serial));assert.notEqual(stateAt(240,{seed:7}).records,stateAt(240,{seed:99}).records);});
test('registration accumulates without batch reset and detailed density increases',()=>{const early=stateAt(0),middle=stateAt(30),late=stateAt(240),later=stateAt(600);assert.equal(early.instances.length,10);assert.ok(middle.instances.length>early.instances.length);assert.ok(late.instances.length>middle.instances.length);assert.ok(later.records>late.records);assert.ok(later.closed>late.closed);assert.equal(desiredDensity(0,1,14),10);assert.equal(desiredDensity(500,1,14),14);});
test('record and geometry counters are derived from real active objects',()=>{for(const t of [0,10,30,60,120,240,600,3600]){const s=stateAt(t),f=frames(s),sum=summary(f,s);assert.equal(sum.records,s.instances.length+s.closed);assert.equal(sum.edges,f.reduce((n,q)=>n+q.activeEdges.length,0));assert.equal(sum.visible,s.instances.length);assert.equal(archiveBundles(s).reduce((n,b)=>n+b.count,0),s.closed);}});
test('archived proxy bundles do not count live records, including out-of-order retirements',()=>{for(let t=55;t<300;t+=7){const s=stateAt(t),bundles=archiveBundles(s,12);assert.ok(bundles.length<=12);assert.equal(bundles.reduce((n,b)=>n+b.count,0),s.closed);for(const b of bundles)assert.equal(b.count,b.to-b.from+1-s.instances.filter(i=>i.serial>=b.from&&i.serial<=b.to).length);}});
test('memory and rendering work remain bounded over a day',()=>{for(const t of [0,600,3600,86400]){const s=stateAt(t,{budget:14});assert.ok(s.instances.length<=14);assert.ok(s.history.length<=8);assert.ok(archiveBundles(s,64).length<=64);assert.equal(s.records,s.closed+s.instances.length);for(const f of frames(s))assert.ok(f.activeEdges.length<=f.model.sourceEdges);}assert.ok(stateAt(86400).records>10000);});
test('lower adaptive budget delays intake without deleting unfinished geometry',()=>{const s=stateAt(240,{budget:14}),serials=s.instances.map(i=>i.serial);setBudget(s,6);assert.deepEqual(s.instances.map(i=>i.serial),serials);advance(s,150);assert.ok(s.instances.length<=6);});
test('pause and reduced-motion stop intake and processing',()=>{const s=createState({reducedMotion:true});advance(s,500);assert.equal(s.elapsed,0);assert.equal(s.records,10);s.paused=false;advance(s,30);assert.ok(s.records>10);});
test('all coordinates remain finite and topology commits continuously',()=>{for(const m of models){const i=makeInstance(m.index+1,0);for(let k=0;k<STEPS.length;k++){const t=i.intro+k*i.stepTime+i.stepTime*.84,a=instanceFrame(m,i,t-1e-5),b=instanceFrame(m,i,t+1e-5);for(let j=0;j<a.vertices.length;j++)for(let n=0;n<3;n++){assert.ok(Number.isFinite(a.vertices[j][n]));assert.ok(Math.abs(a.vertices[j][n]-b.vertices[j][n])<1e-6);}}}});

test('PBR startup offers many more real instances immediately',()=>{assert.equal(createState({budget:26,initialCount:12}).instances.length,12);assert.equal(createState({budget:16,initialCount:8}).instances.length,8);const s=stateAt(600,{budget:26,initialCount:12});assert.ok(s.instances.length>12);assert.ok(s.instances.length<=26);});
