import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {CYCLE,createState,advance,phaseAt,morphAt,anchorAt,prepareModels,sourcePoint,transformPoint,weavePoint} from '../src/simulation.js';
const groups=JSON.parse(readFileSync(new URL('../public/models/sculpture-wireframes.json',import.meta.url))).groups,models=prepareModels(groups);
test('autonomous playback starts without viewer input',()=>{const s=createState();assert.equal(s.paused,false);advance(s,10);assert.equal(s.elapsed,10);assert.equal(phaseAt(10),'unfolding');});
test('reduced motion starts on a still frame',()=>{const s=createState({reducedMotion:true});advance(s,10);assert.equal(s.elapsed,0);});
test('score runs continuously beyond one cycle',()=>{const s=createState();advance(s,200);assert.equal(s.elapsed,200);assert.equal(phaseAt(0),phaseAt(CYCLE));});
test('invalid deltas cannot poison the score',()=>{const s=createState();for(const n of [NaN,Infinity,-1])advance(s,n);assert.equal(s.elapsed,0);});
test('same five models and all original edges are retained',()=>{assert.equal(models.length,5);for(let i=0;i<5;i++){assert.deepEqual(models[i].edges,groups[i].edges);assert.ok(models[i].segments.length>=models[i].edges.length);assert.equal(models[i].segments.length%6,0);}});
test('morphing visibly begins within the first ten seconds',()=>{assert.ok(morphAt(8,0)>.15);assert.ok(morphAt(10,2)>.1);});
test('model phases are staggered rather than synchronized',()=>{assert.notEqual(morphAt(10,0),morphAt(10,3));});
test('all models enter the common line field',()=>{for(let g=0;g<5;g++)for(const y of [0,.5,1])assert.equal(morphAt(38,g,y),1);});
test('every model exactly reforms before the next cycle',()=>{for(const m of models){for(let i=0;i<m.edges.length;i+=Math.max(3,Math.floor(m.edges.length/50/3)*3)){const [x,y,z]=m.edges.slice(i,i+3);if(z===undefined)continue;assert.deepEqual(transformPoint(m,x,y,z,82),sourcePoint(m,x,y,z,82));}}});
test('five sculptures exchange places while within the common field',()=>{for(let g=0;g<5;g++)assert.notDeepEqual(anchorAt(0,g),anchorAt(82,g));});
test('cycle boundaries are geometrically continuous',()=>{for(const m of models)for(let i=0;i<30;i+=3){const [x,y,z]=m.edges.slice(i,i+3),a=transformPoint(m,x,y,z,CYCLE-1e-5),b=transformPoint(m,x,y,z,CYCLE+1e-5);assert.ok(Math.hypot(...a.map((v,k)=>v-b[k]))<.001);}});
test('shared vertices always transform to shared positions',()=>{for(const m of models){const v=m.edges.slice(0,3);assert.deepEqual(transformPoint(m,...v,17.25),transformPoint(m,...v,17.25));}});
test('whole-cycle samples remain finite and bounded',()=>{for(const t of [0,4,10,20,30,38,50,60,72,82,84,100,168,1000])for(const m of models)for(let i=0;i<m.edges.length;i+=60){const p=transformPoint(m,...m.edges.slice(i,i+3),t);assert.ok(p.every(v=>Number.isFinite(v)&&Math.abs(v)<30));}});
test('same-time geometry is deterministic without randomness',()=>{for(const m of models){assert.deepEqual(weavePoint(m,1,1,1,39),weavePoint(m,1,1,1,39));}});
