import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ViewController} from '../src/view-controller.js';
import {GestureController} from '../src/gestures.js';
import {orbitCamera,panCamera,zoomCamera} from '../src/camera.js';
import {cameraBasis} from '../src/flight-camera.js';
const dist=(a,b)=>Math.hypot(...a.map((n,i)=>n-b[i]));
function fixture(){let now=0;const v=new ViewController(),taps=[],g=new GestureController({tap:(...args)=>taps.push(args),navigationStart:()=>v.beginNavigation(now),navigationEnd:()=>v.endNavigation(now),orbit:(x,y)=>{orbitCamera(v.manual,x,y);v.noteNavigation(now);},pan:(x,y)=>{panCamera(v.manual,x,y,1188,762);v.noteNavigation(now);},zoom:f=>{zoomCamera(v.manual,f);v.noteNavigation(now);}});return{v,g,taps,setNow:n=>now=n,frame(dt=1/60,options={}){now+=dt*1000;v.step(dt,now,options);v.markDisplayed();return v.camera;}};}
test('pending touch and repeated taps leave complete camera pose and time identical to uninterrupted playback',()=>{const a=fixture(),b=fixture();for(let frame=0;frame<700;frame++){if(frame%80===10)a.g.down({id:1,x:200,y:300,hit:{serial:8,local:[.2,.3,.4]}});if(frame%80===15)a.g.move({id:1,x:202,y:301});if(frame%80===22)a.g.up(1);assert.deepEqual(a.frame(),b.frame());assert.equal(a.v.time,b.v.time);assert.equal(a.v.lastNavigation,-Infinity);}assert.ok(a.taps.length>5);});
test('drag promotion freezes the last displayed view before applying only the recognized finger movement',()=>{const f=fixture();for(let n=0;n<40;n++)f.frame();const before=f.v.camera,time=f.v.time;f.g.down({id:1,x:100,y:100});f.g.move({id:1,x:112,y:100});assert.equal(f.v.active,true);assert.equal(f.v.base.yaw,before.yaw);assert.ok(Math.abs(f.v.camera.yaw-before.yaw+.096)<1e-9);for(let n=0;n<30;n++)f.frame();assert.equal(f.v.time,time);f.g.up(1);assert.equal(f.v.active,false);assert.equal(f.taps.length,0);for(let n=0;n<200;n++){const eye=cameraBasis(f.v.camera).eye;f.frame();assert.ok(dist(cameraBasis(f.v.camera).eye,eye)<.16);}assert.ok(f.v.time>time);});
test('second finger takes over immediately, cancellation releases once, and no remaining-finger ghost tap occurs',()=>{const f=fixture();f.frame();f.g.down({id:1,x:100,y:100});assert.equal(f.v.active,false);f.g.down({id:2,x:200,y:100});assert.equal(f.v.active,true);f.g.move({id:2,x:220,y:105});f.g.up(2);assert.equal(f.v.active,true);f.g.up(1);assert.equal(f.v.active,false);assert.equal(f.taps.length,0);f.g.down({id:3,x:10,y:10});f.g.move({id:3,x:30,y:10});assert.equal(f.v.active,true);f.g.cancel();assert.equal(f.v.active,false);f.g.up(3);assert.equal(f.taps.length,0);});
test('new drag during automatic return starts from the displayed pose without a base jump',()=>{const f=fixture();for(let n=0;n<200;n++)f.frame();f.g.down({id:1,x:100,y:100});f.g.move({id:1,x:150,y:110});f.g.up(1);for(let n=0;n<160;n++)f.frame();const shown=f.v.camera;f.v.step(.01,6010);f.setNow(6010);f.g.down({id:2,x:100,y:100});f.g.move({id:2,x:107,y:100});assert.ok(Math.abs(f.v.camera.yaw-(shown.yaw-.056))<1e-9);assert.equal(f.v.camera.pitch,shown.pitch);f.g.cancel();});
test('pause and OS reduced motion hold flight and manual pose, while model tap callbacks still work',()=>{for(const options of[{paused:true},{reducedMotion:true}]){const f=fixture();f.frame(0,options);const before=f.v.camera;for(let n=0;n<100;n++)f.frame(1/60,options);assert.deepEqual(f.v.camera,before);f.g.down({id:1,x:1,y:1,hit:null});f.g.up(1);assert.equal(f.taps.length,1);assert.deepEqual(f.v.camera,before);}});
