import { chromium, devices } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const desktop = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors=[];
desktop.on('pageerror', (error) => errors.push(error.message));
desktop.on('console', (msg) => { if(msg.type()==='error') errors.push(msg.text()); });
await desktop.goto('http://localhost:4173');
await desktop.waitForSelector('body[data-status=ready]',{timeout:60000});
await desktop.waitForTimeout(2000);
await desktop.screenshot({path:'test-results/desktop.png'});
await desktop.locator('[data-mode=signal]').click();
await desktop.waitForTimeout(800);
await desktop.screenshot({path:'test-results/signal.png'});
await desktop.locator('[data-view=aperture]').click();
await desktop.waitForTimeout(1600);
await desktop.screenshot({path:'test-results/aperture.png'});
await desktop.locator('[data-mode=monolith]').click();
await desktop.waitForTimeout(300);
await desktop.screenshot({path:'test-results/monolith.png'});
const mobile=await browser.newPage({...devices['iPhone 13'], viewport:{width:390,height:844}});
mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto('http://localhost:4173');
await mobile.waitForSelector('body[data-status=ready]',{timeout:60000});
await mobile.waitForTimeout(1500);
await mobile.screenshot({path:'test-results/mobile.png'});
await mobile.locator('#panel-toggle').click();
await mobile.screenshot({path:'test-results/mobile-menu.png'});
console.log(JSON.stringify({errors, desktopStatus:await desktop.locator('body').getAttribute('data-status'),mobileStatus:await mobile.locator('body').getAttribute('data-status')},null,2));
await browser.close();
